services:

    jaguero.meshicontact.listplugins_eventsubscriber:
        class: Jaguero\MeshiContactBundle\Event\ListPluginsSubscriber
        arguments: ['@router', '@translator']
        tags:
            - { name: kernel.event_subscriber }
